In [2]:
import pandas as pd
dengue = pd.read_csv('dengbr18.csv')

C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_7704\1963926560.py:2: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  dengue = pd.read_csv('dengbr18.csv')

In [3]:
dengue['CLASSI_FIN'].value_counts()
#Aparição do 5 - descartado

CLASSI_FIN
5.0     23050
10.0    12472
8.0      4997
11.0      135
12.0       23
Name: count, dtype: int64

<b>.describe()</b> = média, desvio padrão, máximo, mínimo e outras tendências centrais, além da forma da distribuição.

In [4]:
dengue['CLASSI_FIN'] = dengue['CLASSI_FIN'].fillna('0.0')
dengue['CLASSI_FIN'].describe()

count     40725.0
unique        6.0
top           5.0
freq      23050.0
Name: CLASSI_FIN, dtype: float64

In [5]:
dengue_sintomas = dengue.iloc[:, 23:44]
#dengue_sintomas.value_counts()
dengue_sintomas.describe()

,FEBRE,MIALGIA,CEFALEIA,EXANTEMA,VOMITO,NAUSEA,DOR_COSTAS,CONJUNTVIT,ARTRITE,ARTRALGIA,...,LEUCOPENIA,LACO,DOR_RETRO,DIABETES,HEMATOLOG,HEPATOPAT,RENAL,HIPERTENSA,ACIDO_PEPT,AUTO_IMUNE
count,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,...,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000,38486.000000
mean,1.079977,1.293120,1.186535,1.748376,1.764850,1.657902,1.602505,1.917269,1.837395,1.713298,...,1.964948,1.966897,1.649691,1.983293,1.995375,1.994128,1.995505,1.958712,1.994362,1.996154
std,0.271261,0.455199,0.389543,0.433952,0.424098,0.474419,0.489386,0.275479,0.369009,0.452227,...,0.183913,0.178908,0.477073,0.128174,0.067851,0.076406,0.066896,0.198958,0.074878,0.061894
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,...,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
50%,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
75%,1.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [6]:
dengue_sintomas.isnull().sum()
#Mais valores vazios

FEBRE         2239
MIALGIA       2239
CEFALEIA      2239
EXANTEMA      2239
VOMITO        2239
NAUSEA        2239
DOR_COSTAS    2239
CONJUNTVIT    2239
ARTRITE       2239
ARTRALGIA     2239
PETEQUIA_N    2239
LEUCOPENIA    2239
LACO          2239
DOR_RETRO     2239
DIABETES      2239
HEMATOLOG     2239
HEPATOPAT     2239
RENAL         2239
HIPERTENSA    2239
ACIDO_PEPT    2239
AUTO_IMUNE    2239
dtype: int64

In [7]:
dengue_sintomas = dengue_sintomas.fillna('0')
dengue_sintomas.value_counts()

FEBRE  MIALGIA  CEFALEIA  EXANTEMA  VOMITO  NAUSEA  DOR_COSTAS  CONJUNTVIT  ARTRITE  ARTRALGIA  PETEQUIA_N  LEUCOPENIA  LACO  DOR_RETRO  DIABETES  HEMATOLOG  HEPATOPAT  RENAL  HIPERTENSA  ACIDO_PEPT  AUTO_IMUNE
1.0    1.0      1.0       2.0       2.0     2.0     2.0         2.0         2.0      2.0        2.0         2.0         2.0   2.0        2.0       2.0        2.0        2.0    2.0         2.0         2.0           3512
0      0        0         0         0       0       0           0           0        0          0           0           0     0          0         0          0          0      0           0           0             2239
1.0    2.0      1.0       2.0       2.0     2.0     2.0         2.0         2.0      2.0        2.0         2.0         2.0   2.0        2.0       2.0        2.0        2.0    2.0         2.0         2.0           1539
2.0    2.0      2.0       2.0       2.0     2.0     2.0         2.0         2.0      2.0        2.0         2.0         2.0   2.0        2.0       2.0        2.0        2.0    2.0         2.0         2.0           1489
1.0    1.0      1.0       2.0       2.0     2.0     2.0         2.0         2.0      2.0        2.0         2.0         2.0   1.0        2.0       2.0        2.0        2.0    2.0         2.0         2.0            992
                                                                                                                                                                                                                      ...
                2.0       2.0       2.0     1.0     1.0         1.0         1.0      1.0        2.0         2.0         2.0   2.0        2.0       2.0        2.0        2.0    2.0         2.0         2.0              1
                                                                            2.0      1.0        2.0         2.0         2.0   2.0        1.0       2.0        2.0        2.0    2.0         2.0         2.0              1
                                                                2.0         1.0      1.0        1.0         1.0         2.0   2.0        2.0       2.0        2.0        1.0    2.0         2.0         2.0              1
                                                                                                2.0         2.0         2.0   1.0        2.0       1.0        2.0        2.0    1.0         2.0         2.0              1
                          1.0       1.0     2.0     1.0         2.0         2.0      2.0        2.0         2.0         1.0   2.0        2.0       2.0        2.0        2.0    2.0         2.0         2.0              1
Name: count, Length: 3788, dtype: int64

In [8]:
dengue['CLASSI_FIN'] = dengue['CLASSI_FIN'].astype(float)
dengue_sintomas = dengue_sintomas.astype(float)

In [9]:
x = dengue_sintomas #variavel preditora - entrada
y = dengue['CLASSI_FIN'][x.index] #variavel target - saida


from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=42)

In [10]:
from sklearn.ensemble import ExtraTreesClassifier

modelo = ExtraTreesClassifier()

#Fornecer variáreis para o modelo.
modelo.fit(x_treino, y_treino)
resultado = (modelo.score(x_teste, y_teste)) * 100
print(f'A máquina registrou uma probabilidade de {resultado:.2f}% de acerto.')

A máquina registrou uma probabilidade de 62.30% de acerto.

In [11]:
resultado

62.30152234408251

In [12]:
x_teste[10:40]

,FEBRE,MIALGIA,CEFALEIA,EXANTEMA,VOMITO,NAUSEA,DOR_COSTAS,CONJUNTVIT,ARTRITE,ARTRALGIA,...,LEUCOPENIA,LACO,DOR_RETRO,DIABETES,HEMATOLOG,HEPATOPAT,RENAL,HIPERTENSA,ACIDO_PEPT,AUTO_IMUNE
9769,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
30887,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
9469,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
34939,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
13972,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
19144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19211,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
38192,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
27853,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,...,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
26831,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,...,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
19851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13557,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
8194,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,...,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0
39338,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
1829,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
24692,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,...,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0
30128,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
31776,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
36514,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
35881,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
13302,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
2915,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
32682,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
38060,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,...,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
12250,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
7180,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,...,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
23899,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
8439,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
12617,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,...,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
32244,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [13]:
previsao = modelo.predict(x_teste[10:40])
print(previsao)

[ 5.  5.  5.  5.  5.  8.  5.  5.  5. 10.  8.  5.  5.  5.  5.  5.  5.  5.
  5.  5.  5.  5.  5.  5.  5.  5.  5.  5. 10.  5.]

<b>Dicionário da classificação baseada nos sintomas:</b>
5 - Descartado |  10 - Dengue | 11 - Dengue com sinais de alarme | 12 - Dengue grave | 13 - Chikungunya | 0.0 Células vazias

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

modelos = [
    LogisticRegression(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    SVC()
]

for modelo in modelos:
    modelo.fit(x_treino, y_treino)
    resultado = modelo.score(x_teste, y_teste)
    print(f'{modelo.__class__.__name__} score: {resultado}')

c:\Users\Lua.LUADESKTOP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression score: 0.6285807824521198
DecisionTreeClassifier score: 0.6210509084956621
RandomForestClassifier score: 0.6220330659682436
GradientBoostingClassifier score: 0.6316091013259126
SVC score: 0.6295629399247012

utilizando <b>SelectKBest</b> baseado na coluna de sintomas

In [15]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

f_classif = SelectKBest(score_func = f_classif, k = 5)
fit = f_classif.fit(x, y)
features = fit.transform(x)
print(features)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 ...
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [0. 0. 0. 0. 0.]]

In [16]:
colunas = fit.get_support(indices=True) #Indentificação das caracterísiticas do fit
dengue_sintomas.iloc[:, colunas] #Localização das colunas

       HEMATOLOG  HEPATOPAT  RENAL  ACIDO_PEPT  AUTO_IMUNE
0            2.0        2.0    2.0         2.0         2.0
1            2.0        2.0    2.0         2.0         2.0
2            2.0        2.0    2.0         2.0         2.0
3            2.0        2.0    2.0         2.0         2.0
4            2.0        2.0    2.0         2.0         2.0
...          ...        ...    ...         ...         ...
40720        2.0        2.0    2.0         2.0         2.0
40721        0.0        0.0    0.0         0.0         0.0
40722        2.0        2.0    2.0         2.0         2.0
40723        2.0        2.0    2.0         2.0         2.0
40724        0.0        0.0    0.0         0.0         0.0

[40725 rows x 5 columns]

<b>Visualização baseados nos dados reais utilizados no treinamento e desempenho do modelo. </b> Aproximação daquilo que se relaciona com X e Y

In [17]:
x = dengue_sintomas #variavel preditora - entrada
y = dengue['CLASSI_FIN'][x.index] #variavel target - saida


from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=42)

<b>ExtraTreesClassifier</b>: é um algoritmo de aprendizado supervisionado baseado em ensembles de árvores de decisão. Ele é uma variação do Random Forest que utiliza árvores de decisão adicionais (extra trees) para aumentar a diversidade e, potencialmente, melhorar a precisão e a robustez do modelo. As previsões das árvores são combinadas para formar a previsão final. No aprendizado supervisionado, os dados de treinamento que você fornece ao algoritmo 
incluem as soluções desejadas, chamadas de rótulos.

In [18]:
modelo = ExtraTreesClassifier(n_estimators=100, random_state=42)
modelo.fit(x_treino, y_treino)

#n_estimators = números de árvores de dcisão que serão construídas no ensemble.
#Cada árvore é construída usando um subconjunto aleatório dos dados de treinamento e dos atributos.

ExtraTreesClassifier(random_state=42)

 Os métodos <b>'model.feature_importances_'</b> e <b>'np.argsort(importances)[::-1]'</b> são usados para calcular e ordenar a importância das features (variáveis de colunas) no modelo. A importância de uma feature é uma medida de quão útil foi essa feature na construção das árvores de decisão no ensemble.

In [19]:
import seaborn as sns
import matplotlib.pyplot as plt

previsao = modelo.predict(x_teste)
conf_matrix = confusion_matrix(y_teste, previsao) #matriz de confusão

# Plotar matriz de confusão
plt.figure(figsize=(10,7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Previsão')
plt.ylabel('Verdadeiro')
plt.title('Matriz de Confusão')
plt.show()

NameError: name 'confusion_matrix' is not defined

Matriz de Confusão serve pra avaliar uma precisão de classificação. Equivale ao número de observações conhecidas por estarem no grupo e prevê-se que esteja em outro grupo. O modelo para precisões deve ser alto.